version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    env_file: ./api/.env.docker
    restart: always
    ports:
      - 4002:4002
    depends_on:
      - mongo
    volumes:
      - cdn:/var/www/cdn/bookcars
      - ./bookcars.crt:/etc/ssl/bookcars.crt
      - ./bookcars.key:/etc/ssl/bookcars.key
      - ./bookcars.pem:/etc/ssl/bookcars.pem
      - ./rootCA.crt:/etc/ssl/bookcars.ca.crt

  mongo:
    image: mongo:latest
    command: mongod --tlsMode requireTLS --tlsCertificateKeyFile /etc/ssl/mongodb.pem --tlsCAFile /etc/ssl/rootCA.crt
    restart: always
    environment:
      # Provide your credentials here
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./mongodb.pem:/etc/ssl/mongodb.pem
      - ./rootCA.crt:/etc/ssl/rootCA.crt
      - ./bookcars.pem:/etc/ssl/bookcars.pem

  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - api
    ports:
      - 3001:3001
    volumes:
      - ./bookcars.crt:/etc/ssl/bookcars.crt
      - ./bookcars.key:/etc/ssl/bookcars.key

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - cdn:/var/www/cdn/bookcars
      - ./bookcars.crt:/etc/ssl/bookcars.crt
      - ./bookcars.key:/etc/ssl/bookcars.key
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  cdn:
